import pg from 'pg';
import { DATABASE_URL } from './dbUrl.mjs';


const BEGINNER = [
  "古河渚",
  "冈崎朋也",
  "坂上智代",
  "枣恭介",
  "立华奏",
  "鸣濑白羽",
  "空门苍",
  "䌷·文德斯",
  "能美库特莉亚芙卡",
  "神尾观铃",
  "枣铃",
  "神北小毬",
  "冈崎汐",
  "美坂栞",
  "由依",
  "伊吹风子",
  "藤林杏",
  "一之濑琴美",
  "春原阳平",
  "天王寺瑚太朗",
  "国崎往人",
  "雾岛佳乃",
  "远野美凪",
  "月宫亚由",
  "水濑名雪",
  "泽渡真琴",
  "川澄舞",
  "相泽祐一",
  "直枝理树",
  "来谷唯湖",
  "三枝叶留佳",
  "西园美鱼",
  "朱鹭户沙耶",
  "宫泽谦吾",
  "井之原真人",
  "篝",
  "千里朱音",
  "中津静流",
  "此花露西娅",
  "凤千早",
  "神山识",
  "久岛鸥",
  "鹰原羽依里",
  "神户小鸟",
  "音无结弦",
  "仲村由理",
  "岩泽",
  "星野梦美",
  "神奈备命",
  "阿尔托莉雅·潘德拉贡",
  "远坂凛",
  "卫宫士郎",
  "间桐樱",
  "伊莉雅丝菲尔·冯·爱因兹贝伦",
  "言峰绮礼",
  "库·丘林",
  "卫宫切嗣",
  "远野志贵",
  "爱尔奎特·布伦史塔德",
  "希耶尔",
  "远野秋叶",
  "琥珀",
  "翡翠",
  "莲",
  "苍崎青子",
  "久远寺有珠",
  "静希草十郎",
  "苍崎橙子",
  "牧濑红莉栖",
  "冈部伦太郎",
  "阿万音铃羽",
  "椎名真由理",
  "桥田至",
  "菲利斯·喵喵",
  "漆原琉华",
  "天王寺裕吾",
  "天王寺绹",
  "尾上世莉架",
  "有村雏绘",
  "久野里澪",
  "香月华",
  "来栖乃乃",
  "苍井濑名",
  "西条拓巳",
  "咲畑梨深",
  "冬马和纱",
  "小木曾雪菜",
  "北原春希",
  "和泉千晶",
  "杉浦小春",
  "风冈麻理",
  "白银武",
  "鉴纯夏",
  "御剑冥夜",
  "彩峰慧",
  "榊千鹤",
  "珠濑壬姬",
  "篁唯依",
  "前原圭一",
  "龙宫礼奈",
  "园崎魅音",
  "园崎诗音",
  "古手梨花",
  "北条沙都子",
  "羽入",
  "鹰野三四",
  "富竹次郎",
  "入江京介",
  "大石藏人",
  "赤坂卫",
  "右代宫战人",
  "贝阿朵莉切",
  "右代宫缘寿",
  "右代宫朱志香",
  "右代宫让治",
  "古户绘梨花",
  "嘉音",
  "纱音",
  "玛利亚",
  "宇佐美春",
  "沙耶",
  "水上由岐",
  "高岛柘榴",
  "间宫卓司",
  "间宫羽咲",
  "悠木皆守",
  "音无彩名",
  "淳平",
  "仓式茜",
  "迪奥",
  "法伊",
  "库里斯·霍尔顿",
  "凯伊姆·阿斯托利亚",
  "尤斯蒂娅·阿斯托利亚",
  "艾莉丝·弗萝拉莉亚",
  "仓成武",
  "八神可可",
  "茜崎空",
  "松永沙罗",
  "门仓甲",
  "桐岛蕾",
  "水无月真",
  "诺伊",
  "风见雄二",
  "榊由美子",
  "周防天音",
  "松岛满",
  "入巢莳菜",
  "小岭幸",
  "风见一姬",
  "春寺由梨亚",
  "哈克奥罗",
  "艾露露",
  "阿露露",
  "卡露拉",
  "久远",
  "哈克",
  "猫音",
  "露露缇耶",
  "成步堂龙一",
  "御剑怜侍",
  "绫里真宵",
  "王泥喜法介",
  "牙琉响也",
  "成步堂龙之介",
  "希月心音",
  "苗木诚",
  "雾切响子",
  "日向创",
  "狛枝凪斗",
  "七海千秋",
  "最原终一",
  "赤松枫",
  "春川魔姬",
  "王马小吉",
  "江之岛盾子",
  "十神白夜",
  "腐川冬子",
  "不二咲千寻",
  "朝日奈葵",
  "大神樱",
  "舞园沙耶香",
  "小泉真昼",
  "罪木蜜柑",
  "澪田唯吹",
  "边古山边古",
  "石丸清多夏",
  "叶隐康比吕",
  "桑田怜恩",
  "山田一二三",
  "大和田纹土",
  "田中眼蛇梦",
  "樱小路露娜",
  "大藏游星",
  "花之宫瑞穗",
  "大藏里想奈",
  "玉树樱",
  "神本圆佳",
  "小坂井绫",
  "二阶堂真红",
  "艾莉娜",
  "绫地宁宁",
  "因幡巡",
  "朝武芳乃",
  "常陆茉子",
  "丛雨",
  "蕾娜·莉希特娜瓦",
  "在原七海",
  "三司绫濑",
  "新海天",
  "香坂春风",
  "结城希亚",
  "和泉妃爱",
  "锦明日海",
  "月见坂桐叶",
  "彩濑逢樱",
  "游行寺夜子",
  "九条都",
  "四季夏目",
  "明月栞那",
  "小黑",
  "八六",
  "有坂真白",
  "贝斯莉·罗斯·代斯利",
  "艾佩理雅",
  "保科有希",
  "内藤舞亚",
  "出水和琴",
  "铃木佳奈",
  "鹰仓杏铃",
  "月岛夕莉",
  "八日堂朔莉",
  "一之濑穗波",
  "玖音彩乃",
  "不知火祈",
  "天之川沙夜",
  "花咲乃乃香",
  "爱",
  "朱鹭坂七绪",
  "宫国朱璃",
  "石动雪",
  "四月一日奏恋",
  "北大路可怜",
  "僧间理亚",
  "如月真绫",
  "渡会雏见",
  "安娜莉丝",
  "冷泉院桐香",
  "鹿岛理理",
  "茑町千岁",
  "黑姬结灯",
  "所长",
  "克拉丽丝",
  "龙闲天梨",
  "索菲亚",
  "藤崎诗织",
  "神岸明",
  "濑名爱理",
  "梅丽尔·琳琪",
  "艾莉丝蒂娅・瓦伦贝莉・华蔵寺",
  "冰川里奈",
  "水织静久"
];

const EASY_EXTRA = [
  "饭冢武也",
  "水泽依绪",
  "吉尔伽美什",
  "美杜莎",
  "美狄亚",
  "葛木宗一郎",
  "柳洞一成",
  "藤村大河",
  "间桐慎二",
  "黑樱",
  "弓冢五月",
  "巴雪乃",
  "月咏真那",
  "风间祷子",
  "煌武院悠阳",
  "北条铁平",
  "罗诺威",
  "浅井权三",
  "马庭芦花",
  "露西亚",
  "梅尔特·罗格缇耶",
  "御樱禀",
  "二木佳奈多",
  "笹濑川佐佐美",
  "古河秋生",
  "古河早苗",
  "春原芽衣",
  "宫泽有纪宁",
  "相乐美佐枝",
  "美坂香里",
  "北川润",
  "天野美汐",
  "里叶",
  "小满",
  "藤林椋",
  "西九条灯花",
  "井上晶",
  "吉野晴彦",
  "江坂宗源",
  "今宫新",
  "加岛樱",
  "凤咲夜",
  "九头龙冬彦",
  "花村辉辉",
  "左右田和一",
  "终里赤音",
  "百田解斗",
  "茶柱转子",
  "东条斩美",
  "狱原权太",
  "真宫寺是清",
  "梦野秘密子",
  "星龙马",
  "机望",
  "比屋定真帆",
  "阿万音由季",
  "绪方理奈",
  "森川由绮",
  "虹野沙希",
  "右代宫雾江",
  "右代宫绘羽",
  "右代宫留弗夫",
  "右代宫楼座",
  "右代宫夏妃",
  "右代宫藏臼",
  "美缀绫子",
  "塞拉",
  "莉洁莉特",
  "伊斯坎达尔",
  "社霞",
  "神宫司麻里茂",
  "三谷良一",
  "甘粕真与",
  "野村美希",
  "远野恋",
  "芳乃夏露露",
  "真锅计",
  "白河小鸟",
  "朝仓音梦",
  "芳乃樱",
  "杉并",
  "天枷美春",
  "朝仓音姬",
  "森园立夏",
  "白河萤",
  "南燕",
  "今坂唯笑",
  "桧月彩花",
  "三上智也",
  "音羽香",
  "双海诗音",
  "伊吹美奈裳",
  "雾岛小夜美",
  "黑须彼方",
  "花鸟玲爱",
  "夏海里伽子",
  "速濑水月",
  "广野纮",
  "新藤千寻",
  "雨宫优子",
  "火村夕",
  "羽山瑞希",
  "菲娜·法姆·阿修莱特",
  "夏洛特·海瑟林克",
  "凤条院圣华",
  "川神百代",
  "川神一子",
  "黛由纪江",
  "住吉千里",
  "木场美冬",
  "森下未散",
  "青海衣更",
  "皋月驱",
  "凑斗景明",
  "雪村杏",
  "月岛小恋",
  "白河奈奈佳",
  "朝仓由梦",
  "陵祈",
  "藤原雅",
  "花祭果凛",
  "稻穗信",
  "板垣亚巳",
  "板垣辰子",
  "板垣天使",
  "板垣龙兵",
  "九鬼扬羽",
  "九鬼英雄",
  "九鬼纹白",
  "不死川心",
  "岛津岳人",
  "福本育郎",
  "风间翔一",
  "椎名京",
  "克丽丝卡·比亚切诺娃",
  "大藏衣远",
  "大藏琉美音",
  "朝雾麻衣",
  "朝雾麻亚子",
  "凑斗光",
  "凑斗统",
  "玛丽丝·史黛拉",
  "广野凪",
  "宫村宫子",
  "野乃原结",
  "百野栞",
  "草壁美铃",
  "橘菊理",
  "新海翔",
  "高峰莲夜",
  "右田日日姬",
  "雏衣波莱特",
  "蓑笠凪",
  "仓科明日香",
  "鸢泽美咲",
  "市之濑莉佳",
  "常磐华乃",
  "镰仓诗樱",
  "三广幸",
  "樋口璃璃子",
  "白熊",
  "吾妻夜",
  "东云希",
  "朝仓纯一",
  "水越萌",
  "月城爱丽丝",
  "彩珠菜菜子",
  "艾西亚",
  "天枷美夏",
  "樱内义之",
  "图斯库尔",
  "藤香",
  "胧",
  "柚叶",
  "阿托伊",
  "乌露露",
  "卡谬",
  "贝纳威",
  "克罗",
  "加藤羽未",
  "向坂环",
  "姬百合珊瑚",
  "久寿川莎莎拉",
  "柚原木实",
  "十波由真",
  "笹森花梨",
  "草壁优季",
  "贰大猫丸",
  "索尼娅·内瓦麦",
  "西园寺日寄子",
  "右代宫金蔵",
  "知惠留美子",
  "橘千鹤",
  "日下部麻子",
  "菲奥奈·希尔瓦利亚",
  "莉西娅·德·诺瓦斯·尤利",
  "四叶",
  "赛文",
  "芙铃",
  "雅俐耶妲·费瑞",
  "朵鲁蒂尼妲·费瑞",
  "法珞希黛·佛瑟多",
  "黎瑟西雅·哈萨里利",
  "牙琉雾人",
  "夕神迅",
  "亚双义一真",
  "蕾法·帕德玛·克莱因",
  "那由他·萨德玛迪",
  "巴罗克·范齐克斯",
  "匂坂郁纪",
  "户尾耕司",
  "津久叶瑶",
  "丹保凉子",
  "北斗",
  "干有彦",
  "绫弥一条",
  "足利茶茶丸",
  "大鸟香奈枝",
  "西条七海",
  "岸本绫濑",
  "楠优爱",
  "折原梢",
  "卫宫",
  "美轮椿姬",
  "浅井花音",
  "白鸟水羽",
  "柴门水澄",
  "亚托莉",
  "神白水菜萌",
  "妃玲奈",
  "栗生茜",
  "神凤杏",
  "一之濑美樱",
  "葛木姬乃",
  "琉川纱罗",
  "阳之下葵",
  "日向秀树",
  "橘希实香",
  "杏藤千和",
  "夜月姬织"
];

const EASY = [...new Set([...BEGINNER, ...EASY_EXTRA])];

const ROLE_PRIORITY = { main: 0, primary: 1, side: 2, appears: 3 };

async function main() {
  const client = new pg.Client({ connectionString: DATABASE_URL });
  await client.connect();
  await client.query('set search_path to vndb, public');

  const existing = (await client.query('select name from characters')).rows.map((row) => row.name);
  const existingSet = new Set(existing);
  const missing = [...new Set(EASY)].filter((name) => !existingSet.has(name));
  if (missing.length) {
    console.warn(`[difficulty-direct] names not found in characters table: ${missing.join('、')}`);
  }

  await client.query('begin');
  await client.query(`update characters set difficulties = '["normal"]'`);
  for (const name of EASY) {
    await client.query(`update characters set difficulties = '["easy","normal"]' where name = \$1`, [name]);
  }
  for (const name of BEGINNER) {
    await client.query(`update characters set difficulties = '["beginner","easy","normal"]' where name = \$1`, [name]);
  }
  await client.query('commit');

  const pools = (await client.query(
    `select difficulties, count(*)::int as n from characters group by difficulties order by difficulties`
  )).rows;
  const incomplete = (await client.query(
    `select count(*)::int as n from characters
     where (difficulties like '%beginner%' or difficulties like '%easy%')
       and (gender = '未知' or cv = '未知' or hair_color = '未知' or hair_color_family = 'unknown'
            or hair_length = '未知' or release_year = 0 or work = '未知' or company = '未知')`
  )).rows[0].n;

  const beginnerChars = (await client.query(
    `select vndb_id from characters where difficulties like '%beginner%'`
  )).rows;
  const vns = (await client.query('select id, vid, role from chars_vns')).rows;
  const titles = (await client.query('select id, lang, title from vn_titles')).rows;
  const vnsByChar = new Map();
  for (const row of vns) {
    if (!vnsByChar.has(row.id)) vnsByChar.set(row.id, []);
    vnsByChar.get(row.id).push(row);
  }
  const titlesByVn = new Map();
  for (const row of titles) {
    if (!titlesByVn.has(row.id)) titlesByVn.set(row.id, []);
    titlesByVn.get(row.id).push(row);
  }
  const roleOf = (charId) => {
    const rows = vnsByChar.get(charId) || [];
    if (!rows.length) return 'appears';
    return rows.map((row) => {
      const hasTitle = titlesByVn.has(row.vid);
      const hasZh = titlesByVn.get(row.vid)?.some((t) => t.lang === 'zh-Hans') ?? false;
      return {
        row,
        score: (ROLE_PRIORITY[row.role] ?? 9) * 100 + (hasZh ? 0 : 10) + (hasTitle ? 0 : 20),
      };
    }).sort((a, b) => a.score - b.score)[0].row.role;
  };
  const badRoles = beginnerChars
    .map((row) => ({ vndbId: row.vndb_id, role: roleOf(row.vndb_id) }))
    .filter((entry) => entry.role !== 'main' && entry.role !== 'primary');

  console.log('pools', JSON.stringify(pools, null, 2));
  console.log('incomplete in beginner/easy:', incomplete);
  console.log('beginner non main/primary:', badRoles.length, badRoles.slice(0, 10));
  await client.end();
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
